server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Wc123123
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
      pool-name: mbCodeGeneratorPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1