db:
  driver:
    name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/mb_code_generator_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: Wc123123

ignore:
  table:
    prefix: "true"
  bean:
    # support multiple json handle class
    tojson:
      field: companyId,status
      expression: "@JsonIgnore"
      class: import com.fasterxml.jackson.annotation.JsonIgnore

# date format serialization
bean:
  date:
    format:
      serialization: "@JsonFormat(pattern = \"%s\", timezone = \"GMT+2\")"
      serialization-class: com.fasterxml.jackson.annotation.JsonFormat
      deserialization: "@DateTimeFormat(pattern = \"%s\")"
      deserialization-class: org.springframework.format.annotation.DateTimeFormat

suffix:
  bean:
    param: Query

# base location
path:
  base: D:\Coding\mb-code-generator-workspace\mb-code-generator-demo\src\main

# package name / directory name
package:
  base: com.maimai
  po: entity.po
  vo: entity.vo
  param: entity.query

comment:
  author: maimai