db:
  driver:
    name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/mb_code_generator_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: Wc123123

ignore:
  table:
    prefix: "true"
  bean:
    # support multiple json handle class
    tojson:
      field: companyId,status
      expression: "@JsonIgnore"
      class: import com.fasterxml.jackson.annotation.JsonIgnore

# date format serialization package
bean:
  date:
    format:
      serialization: "@JsonFormat(pattern = \"%s\", timezone = \"GMT+2\")"
      serialization-class: com.fasterxml.jackson.annotation.JsonFormat
      deserialization: "@DateTimeFormat(pattern = \"%s\")"
      deserialization-class: org.springframework.format.annotation.DateTimeFormat

suffix:
  bean:
    query: Query
    fuzzy: Fuzzy
    time:
      start: Start
      end: End
  mapper: Mapper

# base location of project that needs to generate code
path:
  base: D:/Coding/mb-code-generator-workspace/mb-code-generator-demo/src/main


# package name / directory name
package:
  base: com.maimai
  po: entities.po
  vo: entities.vo
  query: entities.query
  utils: utils
  enums: enums
  mappers: mappers
  service: service
  serviceImpl: service.impl
  controller: controller
  exception: exception


comment:
  author: maimai