db:
  driver:
    name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/mb_code_generator_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: Wc123123

ignore:
  table:
    prefix: "true"
suffix:
  bean:
    param: Query

# base location
path:
  base: /Users/yule/Coding/mb-code-generator-workspace/mb-code-generator-demo/src/main

# package name / directory name
package:
  base: com.maimai
  po: entity.po
  param: entity.query